// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA49y_vjXrt5waBXuxcJCjvhxXUC71uoGI',
    appId: '1:591580291450:web:c9dd5ceee067937043b6c3',
    messagingSenderId: '591580291450',
    projectId: 'family-connect-84a74',
    authDomain: 'family-connect-84a74.firebaseapp.com',
    storageBucket: 'family-connect-84a74.firebasestorage.app',
    measurementId: 'G-00VK4CHVN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZFDX9aUeSaENRHlKt3uU7mJQ9aE0T2ko',
    appId: '1:591580291450:android:483bdc6831e47e5943b6c3',
    messagingSenderId: '591580291450',
    projectId: 'family-connect-84a74',
    storageBucket: 'family-connect-84a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Q0oX5lf2jhuxz1SERYEubZolGCkl4uw',
    appId: '1:591580291450:ios:8fa912994522296b43b6c3',
    messagingSenderId: '591580291450',
    projectId: 'family-connect-84a74',
    storageBucket: 'family-connect-84a74.firebasestorage.app',
    iosBundleId: 'com.example.familyConnectStable',
  );
}
